### PR TITLE
Fix for #86

### PR DESCRIPTION
**Pull request by Mushini**
I hope this is about what you wanted. (still in Mhz format)

### CODE REVIEW

**Comment by comzeradd** [comment]
So, following up the last comment on #86, I'd suggest we leave the frequnecy on the MHz format to look nicer and have a tooltip with the full Hz value.

Ideally we should use [Bootstrap's tooltip](http://getbootstrap.com/javascript/#tooltips) to do this.

**Comment by comzeradd** [comment]
Hey @Mushini did you had the time to check this out?

**Comment by Mushini** [comment]
@comzeradd I have been trying to get docker to work with satnogs-db, but I can't figure out why it doesn't. It'll take me awhile longer to try my hand at this, since I'll have to setup a different testing environment - I guess I'll do that if there's nothing wrong with the dockerfile and instructions. Thanks.

**Comment by comzeradd** [comment]
I'm closing this for now. Let me know if I can help with your development setup. I'm on IRC.

**Pull request closed without merging**
