### PR TITLE
Calculate satellite position in frontend from TLE with gpredict.js

### PR DESCRIPTION
**Pull request by kerel-fs**

### CODE REVIEW

**Comment by comzeradd** [comment]
Hey @kerel-fs, any update on this?

**Comment by kerel-fs** [comment]
Yes, linting gpredict.js throws 2101 errors and I have no idea where to start.

**Comment by comzeradd** [comment]
In general we don't lint external libraries, so you don't have to fix all these gpredict errors now. But the two errors left on `map.js` seem to be inherited by gpredict. I can add these as exceptions for now and you can fix them later on gpredict.js.

```
27:19  error  A constructor name should not start with a lowercase letter
41:35  error  A function with a name starting with an uppercase letter should only be used as a constructor
```

So, it's a good practice that functions that are to be used as constructors should start with an uppercase and regular functions should be lowercase. So `sat_t` should be `Sat_t` and `Julian_Date` should be `julian_date` on gpredict.js.

**Comment by comzeradd** [comment]
I'm mostrly interested on what other features we can have with gpredict.js. For instance is it possible to show the satellite trajectory?

**Comment by kerel-fs** [comment]
Yes, it's possible. I added a footprint and the ground track for the next three orbits. The according code was copied from [phonesat-website](https://github.com/cepr/phonesat-website). Screenshot:
screenshot_orbitandfootprint

I didn't understand the footprint code yet, but @csete should be able to (since he is referenced especially in this exact code fragment).

**Comment by kerel-fs** [comment]
Finally I fixed the linting errors by changing the API in gpredict.js upstream, increasing the inconsistency of this js library.
A cleaner solution would be to rewrite gpredict.js to become a proper node-module with a recent library structure. Another solution would be to use another js-library (e.g. satellite.js) for TLE-parsing/SGP4 propagation where this was already done.

For the meantime, I recommend to merge this patch.

PS: The build is failing due to unrelated issue(s).

**Comment by kerel-fs** [comment]
Rebased on latest dev.

**Comment by comzeradd** [comment]
I'll try to squash the commits and rebase the PR before merge.

**Comment by comzeradd** [comment]
@kerel-fs I checked a few satellites and I see multiple orbits. Also the one starting from the satellite is showing the path that the satellite has already crossed but not where is heading to. Is this expected?

screenshot-2017-8-5 satnogs db - 41603 - lapan-a3

**Comment by kerel-fs** [comment]
Multiple orbits is expected, a fixed number of positions `COUNT` with time steps `STEP` inbetween are computed. Currently `COUNT = 300` and `STEP=60 s`. Since positions in the future are calculated (`t.getTime() + STEP`) the ground track should be drawn for current/future orbits. We could easily tweak this and calculate the ground track for both directions (in time).

**Comment by comzeradd** [comment]
Closing this in favor of [#203](https://gitlab.com/librespacefoundation/satnogs/satnogs-db/merge_requests/203)

**Pull request closed without merging**
