### PR TITLE
Fix issue 14 titles of account templates.

### PR DESCRIPTION
**Pull request by ppapadeas**

### CODE REVIEW

**Comment by ppapadeas** [comment]
@comzeradd r?

**Comment by comzeradd** [comment]
It would be better to add an extra space before the dash too. See the [about page](https://github.com/satnogs/satnogs-db/blob/dev/db/templates/base/about.html#L3).

**Comment by ppapadeas** [comment]
PR updated!

**Comment by comzeradd** [comment]
Looks good.

**Pull request merged**
